os:
  - linux
  - osx

addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - cmake

language: c

compiler:
  - gcc
  - clang

script:
  - mkdir _build
  - cd _build
  - cmake ..
  - cmake --build .
  - ctest -VV
