version: 1.0.{build}-{branch}

environment:
  matrix:
    - GENERATOR: "MinGW Makefiles"

configuration:
  - Debug
  - Release

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - mkdir _build
  - cd _build

build_script:
  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest -VV --config %CONFIGURATION%
